// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc service
 * @name ResourceForceAuthoringTool.Auth
 * @description
 * # Auth
 * Service in the ResourceForceAuthoringTool.
 */
angular.module('resourceForceAuthoringTool')
	.factory('Auth', [
				'$rootScope','AuthService', 'CookieService',
		function($rootScope, AuthService, CookieService) {
			var Auth;
			Auth = {
				set: function(userId, name, type) {

					AuthService.login(userId, name, type);
				//	Cookies.set(userId, name, type);
				},
				preApproved: false,
				isLoggedIn: function() {
					console.log(CookieService.test());
					// first see if there are cookies set
					// if (Cookies.get("userId") != null && Cookies.get("name") != null && Cookies.get("type") != null)
					// {
					// 	set(Cookies.get("userId"),Cookies.get("name"), Cookies.get("type"));
					// }
					// else
					// {
						return AuthService.isAuthenticated();
					//}
				},
				getName: function(){
					return AuthService.getUsername();
				},
				getId: function(){
					return AuthService.getId();
				},
				getType: function(){
					return AuthService.getType();
				},
				logout: function() {
				//	Cookies.remove();					
				}
			};
			return Auth;
		}
	]);
