// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc service
 * @name ResourceForceAuthoringTool.Auth
 * @description
 * # Auth
 * Service in the ResourceForceAuthoringTool.
 */
angular.module('resourceForceAuthoringTool')
	.factory('Auth', [
				'$rootScope','AuthService', 'CookieService',
		function($rootScope, AuthService, CookieService) {
			var Auth;
			Auth = {
				set: function(userId, name, type, languages, locations) {

					AuthService.login(userId, name, type, languages, locations);
					CookieService.set(userId, name, type, languages, locations);
				},
				preApproved: false,

				isLoggedIn: function() {
					// first see if there are cookies set
					if (CookieService.exists())
					{
						AuthService.loginWithCookies(CookieService.get());
						return true; 
					}
					else
					{
						return AuthService.isAuthenticated();
					}
				},

				getName: function(){
					return AuthService.getUsername();
				},
				
				getId: function(){
					return AuthService.getId();
				},
				
				getType: function(){
					return AuthService.getType();
				},
				
				getLanguages: function(){
					return AuthService.getLanguages();
				},
				
				getLocations: function(){
					return AuthService.getLocations();
				},
				
				logout: function() {
					AuthService.logout();
					CookieService.remove();					
				}
			};
			return Auth;
		}
	]);
