// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc service
 * @name ResourceForceAuthoringTool.Auth
 * @description
 * # Auth
 * Service in the ResourceForceAuthoringTool.
 */
angular.module('resourceForceAuthoringTool')
	.factory('Auth', [
		'$rootScope',
		'AuthService',
		function($rootScope, AuthService) {
			var Auth;
			Auth = {
				set: function(userId, name, type) {

					AuthService.login(userId, name, type);
				},
				preApproved: false,
				isLoggedIn: function() {
					return AuthService.isAuthenticated();
				},
				getName: function(){
					return AuthService.getUsername();
				},
				getId: function(){
					return AuthService.getId();
				},
				getType: function(){
					return AuthService.getType();
				}
			};
			return Auth;
		}
	]);
