version: '2'

services: 
    resourceforceauthoringtool-mariadb: 
        network_mode: "bridge"
        environment:
            MYSQL_ROOT_PASSWORD: "t0pSECr3t"
        image: mariadb
        container_name: "resourceforceauthoringtool-mariadb"
        expose:
            - 3306
    resourceforceauthoringtool:
        network_mode: "bridge"
        build:
            context: .
        image: "resourceforceauthoringtool"
        container_name: "resourceforceauthoringtool"
        links:
            - resourceforceauthoringtool-mariadb
        expose:
            - 5000
        environment:
            ASPNETCORE_URLS: "http://0.0.0.0:5000"
