version: '2'

services: 
    resourceforceauthoringtool-v1-mariadb: 
        network_mode: "bridge"
        environment:
            MYSQL_ROOT_PASSWORD: "t0pSECr3t"
        image: mariadb
        container_name: "resourceforceauthoringtool-v1-mariadb"
        expose:
            - 3306
        ports:
            - "45301:3306"
    resourceforceauthoringtool-v1:
        network_mode: "bridge"
        build:
            context: .
        image: "resourceforceauthoringtool-v1"
        container_name: "resourceforceauthoringtool-v1"
        links:
            - resourceforceauthoringtool-v1-mariadb
        expose:
            - 5000
        environment:
            ASPNETCORE_URLS: "http://0.0.0.0:5000"
