// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using PlayGen.ResourceForceAuthoringTool.Data.EntityFramework;
using System;

namespace PlayGen.ResourceForceAuthoringTool.Data.EntityFramework.Migrations
{
    [DbContext(typeof(RFContext))]
    partial class RFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("PlayGen.ResourceForceAuthoringTool.Data.Model.AccountRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Languages");

                    b.Property<string>("Locations");

                    b.Property<string>("MemberType");

                    b.Property<int>("PlayerId");

                    b.Property<string>("Reason")
                        .HasAnnotation("MySQL:Charset", "utf8");

                    b.HasKey("Id");

                    b.ToTable("AccountRequests");

                    b.HasAnnotation("MySQL:Collation", "utf8_bin");
                });

            modelBuilder.Entity("PlayGen.ResourceForceAuthoringTool.Data.Model.Scenario", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Comment")
                        .HasAnnotation("MySQL:Charset", "utf8");

                    b.Property<string>("Content")
                        .HasColumnType("mediumtext")
                        .HasAnnotation("MySQL:Charset", "utf8");

                    b.Property<int>("CreatorId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("Deleted");

                    b.Property<bool>("IsValid");

                    b.Property<string>("Language");

                    b.Property<string>("Location");

                    b.Property<long>("SerialNumber");

                    b.Property<bool>("Submitted");

                    b.Property<string>("Title")
                        .HasAnnotation("MySQL:Charset", "utf8");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");

                    b.HasAnnotation("MySQL:Collation", "utf8_bin");
                });

            modelBuilder.Entity("PlayGen.ResourceForceAuthoringTool.Data.Model.SerialNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Number");

                    b.HasKey("Id");

                    b.ToTable("SerialNumbers");
                });

            modelBuilder.Entity("PlayGen.ResourceForceAuthoringTool.Data.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Languages");

                    b.Property<string>("Locations");

                    b.Property<string>("MemberType");

                    b.Property<string>("Password");

                    b.Property<string>("Username")
                        .HasAnnotation("MySQL:Charset", "utf8");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasAnnotation("MySQL:Collation", "utf8_bin");
                });
#pragma warning restore 612, 618
        }
    }
}
